[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "queue-processor"
dynamic = ["version"]
description = "Manage queues on Uwazi services"
license = { file = "LICENSE" }
authors = [{ name = "HURIDOCS" }]
requires-python = ">= 3.10"
dependencies = [
    "PyRSMQ==0.6.0",
    "redis==5.0.7",
    "pydantic==2.12.5"
]

[project.urls]
HURIDOCS = "https://huridocs.org"
GitHub = "https://github.com/huridocs/queue-processor"

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "no-local-version"
write_to = "_version.py"
tag_regex = "^(?P<prefix>v)?(?P<version>\\d+(?:\\.\\d+)*)$"